### ISSUE TITLE
Can't set headers after they are sent.

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [i18next/i18next-express-middleware#138]
```
Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:359:11)
    at Cookies.set (/node_modules/cookies/index.js:115:13)
    at Object.cacheUserLanguage (/node_modules/i18next-express-middleware/lib/languageLookups/cookie.js:42:15)
    at /Users/admin/Projects/bankaletihad/node_modules/i18next-express-middleware/lib/LanguageDetector.js:127:119
    at Array.forEach (native)
    at LanguageDetector.cacheUserLanguage (/node_modules/i18next-express-middleware/lib/LanguageDetector.js:126:14)
    at /node_modules/i18next-express-middleware/lib/index.js:41:43
    at /node_modules/i18next/dist/commonjs/EventEmitter.js:52:18
    at Array.forEach (native)
    at I18n.emit (/node_modules/i18next/dist/commonjs/EventEmitter.js:51:14)
```

It looks like caches: ['cookie'] cause a memory leak issue. 
```
detection: {
    order: ['session', 'cookie', 'navigator', 'htmlTag'],
    lookupCookie: 'lang',
    caches: ['cookie']
  }

```

**Comment by jamuhl** [comment]
looks like you change language after request ends

**Comment by Iuriy-Budnikov** [comment]
yeah, thanks. strange after removing caches: ['cookie'] works fine.

**Comment by Iuriy-Budnikov** [comment]
if somebody will face with the same issue. you will need to use custom detector. 


```
import Cookies from 'cookies';
import langs from './langs';

module.exports = {
  name: 'url',


  lookup: (req, res) => {
    let locale = langs[0].value;
    if (typeof req !== 'undefined') {
      const lng = req.url.split('/');
      locale = (lng && lng[1]) || req.language.split('-')[0];
    }
    return locale;
  },

  cacheUserLanguage: (req, res, lng, options) => {
    if (options.lookupCookie && req !== 'undefined' && req.cookies.lang !== lng) {
      const cookies = new Cookies(req, res);
      let expirationDate = options.cookieExpirationDate;
      if (!expirationDate) {
        expirationDate = new Date();
        expirationDate.setFullYear(expirationDate.getFullYear() + 1);
      }
      cookies.set(options.lookupCookie, lng, { expires: expirationDate, domain: options.cookieDomain, httpOnly: false, overwrite: true });
    }
  }
};
```
