### ISSUE TITLE
How to use i18nextMiddleware.addRoute?

### ISSUE THREAD

**Issue by nagman** [i18next/i18next-express-middleware#158]
There is absolutely no docs on this method whereas it's vital for SEO purposes.
What should I put in the callback function?
How can I pass the language to react-i18next?

Isn't it simpler to use basic express routing?

**Comment by adrai** [comment]
req, res => https://github.com/i18next/i18next-express-middleware/issues/123

**Comment by nagman** [comment]
There's no explanation on how it works and a simple copy/paste doesn't work.
After diving into the source code, I started to figure it out.
Now I can see an error (I had nothing before).

Here's my route:
```
i18nextMiddleware.addRoute(
  i18n,
  '/:lng/index',
  langs,
  server,
  'get',
  (req, res) => app.render(req, res, '/index', {}),
);
```

When I try to access to `/fr/index`, it throws me:
```
{ TypeError: Cannot set property 'toJSON' of undefined
    at I18n.module.exports.10.i18n.getInitialProps (/mnt/c/Users/Adelios/Desktop/hivency-v2/.next/server/bundles/pages/_error.js:200:19)
    at Function._callee$ (/mnt/c/Users/Adelios/Desktop/hivency-v2/.next/server/bundles/pages/index.js:137:92)
    at tryCatch (/mnt/c/Users/Adelios/Desktop/hivency-v2/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/mnt/c/Users/Adelios/Desktop/hivency-v2/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/mnt/c/Users/Adelios/Desktop/hivency-v2/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/mnt/c/Users/Adelios/Desktop/hivency-v2/.next/server/bundles/pages/index.js:97:221)
    at _next (/mnt/c/Users/Adelios/Desktop/hivency-v2/.next/server/bundles/pages/index.js:97:409)
    at /mnt/c/Users/Adelios/Desktop/hivency-v2/.next/server/bundles/pages/index.js:97:477
    at new Promise (<anonymous>)
    at Function.<anonymous> (/mnt/c/Users/Adelios/Desktop/hivency-v2/.next/server/bundles/pages/index.js:97:97) sourceMapsApplied: true }
```

**Comment by adrai** [comment]
never used addRoute with next.js myself...
Seems like something like this: https://github.com/zeit/next.js/blob/canary/examples/with-react-i18next/i18n.js#L42 is executed without or before this: https://github.com/zeit/next.js/blob/canary/examples/with-react-i18next/server.js#L33
that’s why there is no i18n property attached to req.

**Comment by nagman** [comment]
Just solved it!
Actually you need to call the addRoute method __after__ `server.use(i18nextMiddleware.handle(i18n));`.
My god! I can't believe I made it work after hours of endless pain 🎉 

When this website will be ended, I'll post the whole solution here.

**Comment by situplastik** [comment]
Hi @nagman !
Could you please share your entire code? I have the same problem and finding the solution taking code from differents issues isn't as easy as could be.

Many thanks!

**Comment by nagman** [comment]
Hi @situplastik !
Here it is: https://github.com/i18next/react-i18next/issues/517#issuecomment-438004776
