### ISSUE TITLE
Not working when using something else than i18next as variable

### ISSUE THREAD

**Issue by lenovouser** [i18next/i18next-express-middleware#48]
I am migrating from `v1.11.x` and have required i18next like this:

```js
const i18n = require('i18next');
```

when I do this I get this error from the express-middleware though:

```
TypeError: i18next.t is not a function
    at Object.addRoute (homepage\node_modules\i18next-express-middleware\lib\index.js:176:31)
    at homepage\lib\routes\index.js:51:24
    at homepage\node_modules\i18next\dist\commonjs\i18next.js:190:9
    at done homepage\node_modules\i18next\dist\commonjs\i18next.js:269:21)
    at Object.callback homepage\node_modules\i18next\dist\commonjs\i18next.js:290:7)
    at homepage\node_modules\i18next\dist\commonjs\BackendConnector.js:146:29
    at Array.forEach (native)
    at Connector.loaded homepage\node_modules\i18next\dist\commonjs\BackendConnector.js:139:16)
    at homepage\node_modules\i18next\dist\commonjs\BackendConnector.js:240:22
    at homepage\node_modules\i18next\dist\commonjs\BackendConnector.js:173:7
    at homepage\node_modules\i18next-node-fs-backend\lib\index.js:104:9
    at homepage\node_modules\i18next-node-fs-backend\lib\index.js:67:7
    at tryToString (fs.js:414:3)                              
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

Is there any way I can use the middleware without renaming everything from `i18n` to `i18next`?

**Comment by jamuhl** [comment]
i don't think it has to do with naming of variable.

the error states that i18next.t is undefined...this is a variable inside the middleware module and has nothing todo with your variable required.

did you correctly wire stuff up? https://github.com/i18next/i18next-express-middleware#wire-up-i18next-to-request-object

mainly pass i18next to the middleware.handle?!?

**Comment by lenovouser** [comment]
@jamuhl I do indeed use

```js
app.use(i18nmiddleware.handle(i18n, {
  ignoreRoutes: ["/socket.io"],
  removeLngFromUrl: false
}));
```

I think the problem is in this line [i18next-express-middleware/src/index.js#L32](https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L32), even though I am not a JavaScript pro. It calls the function `i18next.t()` which in my case doesn't even exist, as I use `i18n.t()` because I required `i18next` like this:

```js
const i18n = require('i18next');
```

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L6 there is i18next param -> this is what you pass in `app.use(i18nmiddleware.handle(i18n,...`

try:
```
const i18n = require('i18next');
console.log(i18n.t, i18n);
```

really seems your i18n is undefined

**Comment by lenovouser** [comment]
@jamuhl output of the `console.log`:

```js
[Function: t] I18n {
  observers: {},
  options:
   { debug: false,
     ns:
      [ 'main',
        'home',
        'team',
        'status',
        'legal',
        'user',
        'statistics',
        'pages',
        'navbar',
        'footer',
        'time',
        'meta',
        'auth',
        'rank' ],
     defaultNS:
      [ 'main',
        'home',
        'team',
        'status',
        'legal',
        'user',
        'statistics',
        'pages',
        'navbar',
        'footer',
        'time',
        'meta',
        'auth',
        'rank' ],
     fallbackLng: [ 'en' ],
     fallbackNS: false,
     whitelist: undefined,
     load: 'all',
     preload: [ 'en', 'de', 'ko' ],
     keySeparator: undefined,
     nsSeparator: undefined,
     pluralSeparator: '_',
     contextSeparator: '_',
     saveMissing: undefined,
     saveMissingTo: 'en',
     missingKeyHandler: false,
     postProcess: false,
     returnNull: true,
     returnEmptyString: true,
     returnObjects: undefined,
     joinArrays: '\n',
     returnedObjectHandler: undefined,
     parseMissingKeyHandler: undefined,
     appendNamespaceToMissingKey: true,
     overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
     interpolation:
      { unescapeSuffix: 'HTML',
        prefix: '__',
        suffix: '__',
        escapeValue: false,
        nestingPrefix: '$t(',
        nestingSuffix: ')' },
     compatibilityAPI: 'v1',
     compatibilityJSON: 'v1',
     defaultNs: 'main',
     backend:
      { loadPath: 'locales/__lng__/__ns__.json',
        addPath: 'locales/add/__lng__/__ns__',
        allowMultiLoading: undefined },
     escapeInterpolation: false,
     sendMissingTo: 'en',
     detectLngQS: 'language',
     lngs: [ 'en', 'de', 'ko' ],
     lookupCookie: '_io.domain.language',
     lookupSession: 'language',
     cookieName: '_io.domain.language',
     cookieDomain: 'domain.tld',
     cache: { prefix: 'res_', expirationTime: 604800000, enabled: false } },
  services:
   { logger:
      Logger {
        subs: [Object],
        prefix: 'i18next:',
        logger: [Object],
        options: [Object],
        debug: false },
     resourceStore: ResourceStore { observers: [Object], data: {}, options: [Object] },
     languageUtils: LanguageUtil { options: [Object], whitelist: false, logger: [Object] },
     pluralResolver:
      PluralResolver {
        languageUtils: [Object],
        options: [Object],
        logger: [Object],
        rules: [Object] },
     interpolator:
      Interpolator {
        logger: [Object],
        options: [Object],
        escapeValue: false,
        prefix: '__',
        suffix: '__',
        unescapePrefix: '',
        unescapeSuffix: 'HTML',
        nestingPrefix: '\\$t\\(',
        nestingSuffix: '\\)',
        regexp: /__(.+?)__/g,
        regexpUnescape: /__(.+?)HTML__/g,
        nestingRegexp: /\$t\((.+?)\)/g },
     backendConnector:
      Connector {
        observers: [Object],
        backend: [Object],
        store: [Object],
        services: [Circular],
        options: [Object],
        logger: [Object],
        state: {},
        queue: [] },
     cacheConnector:
      Connector {
        observers: [Object],
        cache: undefined,
        store: [Object],
        services: [Circular],
        options: [Object],
        logger: [Object] },
     languageDetector:
      LanguageDetector {
        type: 'languageDetector',
        detectors: [Object],
        services: [Circular],
        options: [Object],
        allOptions: [Object] } },
  logger:
   Logger {
     subs: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
     prefix: 'i18next:',
     logger:
      { type: 'logger',
        log: [Function: log],
        warn: [Function: warn],
        error: [Function: error],
        _output: [Function: _output] },
     options:
      { debug: false,
        ns: [Object],
        defaultNS: [Object],
        fallbackLng: [Object],
        fallbackNS: false,
        whitelist: undefined,
        load: 'all',
        preload: [Object],
        keySeparator: undefined,
        nsSeparator: undefined,
        pluralSeparator: '_',
        contextSeparator: '_',
        saveMissing: undefined,
        saveMissingTo: 'en',
        missingKeyHandler: false,
        postProcess: false,
        returnNull: true,
        returnEmptyString: true,
        returnObjects: undefined,
        joinArrays: '\n',
        returnedObjectHandler: undefined,
        parseMissingKeyHandler: undefined,
        appendNamespaceToMissingKey: true,
        overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
        interpolation: [Object],
        compatibilityAPI: 'v1',
        compatibilityJSON: 'v1',
        defaultNs: 'main',
        backend: [Object],
        escapeInterpolation: false,
        sendMissingTo: 'en',
        detectLngQS: 'language',
        lngs: [Object],
        lookupCookie: '_io.domain.language',
        lookupSession: 'language',
        cookieName: '_io.domain.language',
        cookieDomain: 'domain.tld',
        cache: [Object] },
     debug: false },
  modules:
   { languageDetector: { [Function: LanguageDetector] type: 'languageDetector' },
     backend: { [Function: Backend] type: 'backend' } },
  store:
   ResourceStore {
     observers: { added: [Object], removed: [Object] },
     data: {},
     options:
      { debug: false,
        ns: [Object],
        defaultNS: [Object],
        fallbackLng: [Object],
        fallbackNS: false,
        whitelist: undefined,
        load: 'all',
        preload: [Object],
        keySeparator: undefined,
        nsSeparator: undefined,
        pluralSeparator: '_',
        contextSeparator: '_',
        saveMissing: undefined,
        saveMissingTo: 'en',
        missingKeyHandler: false,
        postProcess: false,
        returnNull: true,
        returnEmptyString: true,
        returnObjects: undefined,
        joinArrays: '\n',
        returnedObjectHandler: undefined,
        parseMissingKeyHandler: undefined,
        appendNamespaceToMissingKey: true,
        overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
        interpolation: [Object],
        compatibilityAPI: 'v1',
        compatibilityJSON: 'v1',
        defaultNs: 'main',
        backend: [Object],
        escapeInterpolation: false,
        sendMissingTo: 'en',
        detectLngQS: 'language',
        lngs: [Object],
        lookupCookie: '_io.domain.language',
        lookupSession: 'language',
        cookieName: '_io.domain.language',
        cookieDomain: 'domain.tld',
        cache: [Object] } },
  translator:
   Translator {
     observers: { '*': [Object] },
     resourceStore: ResourceStore { observers: [Object], data: {}, options: [Object] },
     languageUtils: LanguageUtil { options: [Object], whitelist: false, logger: [Object] },
     pluralResolver:
      PluralResolver {
        languageUtils: [Object],
        options: [Object],
        logger: [Object],
        rules: [Object] },
     interpolator:
      Interpolator {
        logger: [Object],
        options: [Object],
        escapeValue: false,
        prefix: '__',
        suffix: '__',
        unescapePrefix: '',
        unescapeSuffix: 'HTML',
        nestingPrefix: '\\$t\\(',
        nestingSuffix: '\\)',
        regexp: /__(.+?)__/g,
        regexpUnescape: /__(.+?)HTML__/g,
        nestingRegexp: /\$t\((.+?)\)/g },
     backendConnector:
      Connector {
        observers: [Object],
        backend: [Object],
        store: [Object],
        services: [Object],
        options: [Object],
        logger: [Object],
        state: {},
        queue: [] },
     options:
      { debug: false,
        ns: [Object],
        defaultNS: [Object],
        fallbackLng: [Object],
        fallbackNS: false,
        whitelist: undefined,
        load: 'all',
        preload: [Object],
        keySeparator: undefined,
        nsSeparator: undefined,
        pluralSeparator: '_',
        contextSeparator: '_',
        saveMissing: undefined,
        saveMissingTo: 'en',
        missingKeyHandler: false,
        postProcess: false,
        returnNull: true,
        returnEmptyString: true,
        returnObjects: undefined,
        joinArrays: '\n',
        returnedObjectHandler: undefined,
        parseMissingKeyHandler: undefined,
        appendNamespaceToMissingKey: true,
        overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
        interpolation: [Object],
        compatibilityAPI: 'v1',
        compatibilityJSON: 'v1',
        defaultNs: 'main',
        backend: [Object],
        escapeInterpolation: false,
        sendMissingTo: 'en',
        detectLngQS: 'language',
        lngs: [Object],
        lookupCookie: '_io.domain.language',
        lookupSession: 'language',
        cookieName: '_io.domain.language',
        cookieDomain: 'domain.tld',
        cache: [Object] },
     logger:
      Logger {
        subs: [],
        prefix: 'i18next::translator:',
        logger: [Object],
        options: [Object],
        debug: false } },
  getResource: [Function],
  addResource: [Function],
  addResources: [Function],
  addResourceBundle: [Function],
  removeResourceBundle: [Function],
  hasResourceBundle: [Function],
  getResourceBundle: [Function],
  lng: [Function],
  preload: [Function],
  setLng: [Function],
  addPostProcessor: [Function] }
```

so it doesn't seem to be undefined. Is this something helpful to you, or do you need something else?

**Comment by jamuhl** [comment]
defaultNS has to be a string

**Comment by jamuhl** [comment]
but that does not solve your problem...

can you go to your node_modules/i18next folder and add https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L6 a console.log there...(should be in dist/commonjs subfolder)


really don't understand where it gets lost...

**Comment by lenovouser** [comment]
You want me to add the the `console.log(i18n.t, i18n);` to `node_modules/i18next/dist/commonjs/index.js` line 6?

**Comment by lenovouser** [comment]
I added it to the `node_modules/i18next-express-middleware/lib/index.js` directly in the handler and modified it to `console.log(i18next.t, i18next);` like this:

![](https://puu.sh/o0MaG/e436405856.png)

because that is what I think you meant. The output is the following:

```js
[Function: t] I18n {
  observers: {},
  options:
   { debug: false,
     ns:
      [ 'main',
        'home',
        'team',
        'status',
        'legal',
        'user',
        'statistics',
        'pages',
        'navbar',
        'footer',
        'time',
        'meta',
        'auth',
        'rank' ],
     defaultNS: 'main',
     fallbackLng: [ 'en' ],
     fallbackNS: [ 'main' ],
     whitelist: [ 'en', 'de', 'ko', 'cimode' ],
     load: 'all',
     preload: [ 'en', 'de', 'ko', 'cimode' ],
     keySeparator: '.',
     nsSeparator: ':',
     pluralSeparator: '_',
     contextSeparator: '_',
     saveMissing: false,
     saveMissingTo: 'fallback',
     missingKeyHandler: false,
     postProcess: false,
     returnNull: true,
     returnEmptyString: true,
     returnObjects: false,
     joinArrays: false,
     returnedObjectHandler: [Function: returnedObjectHandler],
     parseMissingKeyHandler: false,
     appendNamespaceToMissingKey: false,
     overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
     interpolation:
      { escapeValue: true,
        prefix: '{{',
        suffix: '}}',
        unescapePrefix: '-',
        nestingPrefix: '$t(',
        nestingSuffix: ')',
        defaultVariables: undefined },
     backend:
      { loadPath: 'locales/homepage/{{lng}}/{{ns}}.json',
        addPath: null },
     escapeInterpolation: false,
     sendMissingTo: 'en',
     detectLngQS: 'language',
     lngs: [ 'en', 'de', 'ko', 'cimode' ],
     lookupCookie: '_io.domain.language',
     lookupSession: 'language',
     cookieName: '_io.domain.language',
     cookieDomain: 'domain.tld' },
  services:
   { logger:
      Logger {
        subs: [Object],
        prefix: 'i18next:',
        logger: [Object],
        options: [Object],
        debug: false },
     resourceStore: ResourceStore { observers: [Object], data: {}, options: [Object] },
     languageUtils: LanguageUtil { options: [Object], whitelist: [Object], logger: [Object] },
     pluralResolver:
      PluralResolver {
        languageUtils: [Object],
        options: [Object],
        logger: [Object],
        rules: [Object] },
     interpolator:
      Interpolator {
        logger: [Object],
        options: [Object],
        escapeValue: true,
        prefix: '\\{\\{',
        suffix: '\\}\\}',
        unescapePrefix: '-',
        unescapeSuffix: '',
        nestingPrefix: '\\$t\\(',
        nestingSuffix: '\\)',
        regexp: /\{\{(.+?)\}\}/g,
        regexpUnescape: /\{\{-(.+?)\}\}/g,
        nestingRegexp: /\$t\((.+?)\)/g },
     backendConnector:
      Connector {
        observers: [Object],
        backend: [Object],
        store: [Object],
        services: [Circular],
        options: [Object],
        logger: [Object],
        state: {},
        queue: [] },
     cacheConnector:
      Connector {
        observers: [Object],
        cache: undefined,
        store: [Object],
        services: [Circular],
        options: [Object],
        logger: [Object] },
     languageDetector:
      LanguageDetector {
        type: 'languageDetector',
        detectors: [Object],
        services: [Circular],
        options: [Object],
        allOptions: [Object] } },
  logger:
   Logger {
     subs: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
     prefix: 'i18next:',
     logger:
      { type: 'logger',
        log: [Function: log],
        warn: [Function: warn],
        error: [Function: error],
        _output: [Function: _output] },
     options:
      { debug: false,
        ns: [Object],
        defaultNS: 'main',
        fallbackLng: [Object],
        fallbackNS: [Object],
        whitelist: [Object],
        load: 'all',
        preload: [Object],
        keySeparator: '.',
        nsSeparator: ':',
        pluralSeparator: '_',
        contextSeparator: '_',
        saveMissing: false,
        saveMissingTo: 'fallback',
        missingKeyHandler: false,
        postProcess: false,
        returnNull: true,
        returnEmptyString: true,
        returnObjects: false,
        joinArrays: false,
        returnedObjectHandler: [Function: returnedObjectHandler],
        parseMissingKeyHandler: false,
        appendNamespaceToMissingKey: false,
        overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
        interpolation: [Object],
        backend: [Object],
        escapeInterpolation: false,
        sendMissingTo: 'en',
        detectLngQS: 'language',
        lngs: [Object],
        lookupCookie: '_io.domain.language',
        lookupSession: 'language',
        cookieName: '_io.domain.language',
        cookieDomain: 'domain.tld' },
     debug: false },
  modules:
   { languageDetector: { [Function: LanguageDetector] type: 'languageDetector' },
     backend: { [Function: Backend] type: 'backend' } },
  store:
   ResourceStore {
     observers: { added: [Object], removed: [Object] },
     data: {},
     options:
      { debug: false,
        ns: [Object],
        defaultNS: 'main',
        fallbackLng: [Object],
        fallbackNS: [Object],
        whitelist: [Object],
        load: 'all',
        preload: [Object],
        keySeparator: '.',
        nsSeparator: ':',
        pluralSeparator: '_',
        contextSeparator: '_',
        saveMissing: false,
        saveMissingTo: 'fallback',
        missingKeyHandler: false,
        postProcess: false,
        returnNull: true,
        returnEmptyString: true,
        returnObjects: false,
        joinArrays: false,
        returnedObjectHandler: [Function: returnedObjectHandler],
        parseMissingKeyHandler: false,
        appendNamespaceToMissingKey: false,
        overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
        interpolation: [Object],
        backend: [Object],
        escapeInterpolation: false,
        sendMissingTo: 'en',
        detectLngQS: 'language',
        lngs: [Object],
        lookupCookie: '_io.domain.language',
        lookupSession: 'language',
        cookieName: '_io.domain.language',
        cookieDomain: 'domain.tld' } },
  translator:
   Translator {
     observers: { '*': [Object] },
     resourceStore: ResourceStore { observers: [Object], data: {}, options: [Object] },
     languageUtils: LanguageUtil { options: [Object], whitelist: [Object], logger: [Object] },
     pluralResolver:
      PluralResolver {
        languageUtils: [Object],
        options: [Object],
        logger: [Object],
        rules: [Object] },
     interpolator:
      Interpolator {
        logger: [Object],
        options: [Object],
        escapeValue: true,
        prefix: '\\{\\{',
        suffix: '\\}\\}',
        unescapePrefix: '-',
        unescapeSuffix: '',
        nestingPrefix: '\\$t\\(',
        nestingSuffix: '\\)',
        regexp: /\{\{(.+?)\}\}/g,
        regexpUnescape: /\{\{-(.+?)\}\}/g,
        nestingRegexp: /\$t\((.+?)\)/g },
     backendConnector:
      Connector {
        observers: [Object],
        backend: [Object],
        store: [Object],
        services: [Object],
        options: [Object],
        logger: [Object],
        state: {},
        queue: [] },
     options:
      { debug: false,
        ns: [Object],
        defaultNS: 'main',
        fallbackLng: [Object],
        fallbackNS: [Object],
        whitelist: [Object],
        load: 'all',
        preload: [Object],
        keySeparator: '.',
        nsSeparator: ':',
        pluralSeparator: '_',
        contextSeparator: '_',
        saveMissing: false,
        saveMissingTo: 'fallback',
        missingKeyHandler: false,
        postProcess: false,
        returnNull: true,
        returnEmptyString: true,
        returnObjects: false,
        joinArrays: false,
        returnedObjectHandler: [Function: returnedObjectHandler],
        parseMissingKeyHandler: false,
        appendNamespaceToMissingKey: false,
        overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
        interpolation: [Object],
        backend: [Object],
        escapeInterpolation: false,
        sendMissingTo: 'en',
        detectLngQS: 'language',
        lngs: [Object],
        lookupCookie: '_io.domain.language',
        lookupSession: 'language',
        cookieName: '_io.domain.language',
        cookieDomain: 'domain.tld' },
     logger:
      Logger {
        subs: [],
        prefix: 'i18next::translator:',
        logger: [Object],
        options: [Object],
        debug: false } },
  getResource: [Function],
  addResource: [Function],
  addResources: [Function],
  addResourceBundle: [Function],
  removeResourceBundle: [Function],
  hasResourceBundle: [Function],
  getResourceBundle: [Function] }
```

**Comment by jamuhl** [comment]
sorry just yet saw:

```
TypeError: i18next.t is not a function
    at Object.addRoute (homepage\node_modules\i18next-express-middleware\lib\index.js:176:31)
```

do you call `addRoute` without i18next as first param?

https://github.com/i18next/i18next-express-middleware#add-localized-routes

**Comment by lenovouser** [comment]
@jamuhl yes, I did. Totally sorry - really appreciate your help! The detection now not working though `i18n.language` is undefined and it always uses the fallback language.

**Comment by jamuhl** [comment]
did you add the language detector? https://github.com/i18next/i18next-express-middleware#wire-up-i18next-to-request-object

```
i18next
  .use(middleware.LanguageDetector) // language detection magic
  .init(i18nextOptions);
```

**Comment by lenovouser** [comment]
Yes, I do. I uploaded the whole file to [hastebin.com/routes.js](http://hastebin.com/jiqaduxeyo.js) so that you can see all of it. This file just gets called from `app.js` by using `const Routes = require('lib/routes')(app);`

**Comment by jamuhl** [comment]
ah....you test language on i18next instance...that will not be set.

every request will get the language set through the middleware.handle inside the request you can access req.language and req.t => those are safe to use...

or do you mean req.language is undefined?

setting language and using t of the i18next instance would result in wrong translations - as async request would influence each other.

**Comment by lenovouser** [comment]
@jamuhl I mean that the language is undefined. If I add

```js
console.log('Current language used: ' + i18n.language);
```

after the handle it returns `undefined`

**Comment by jamuhl** [comment]
yes...like said...on i18next language will be undefined....as using language set on a singleton is useless in async env.

http://ejohn.org/blog/a-strategy-for-i18n-and-node/ --> check i18n logic section to understand

**Comment by lenovouser** [comment]
@jamuhl did anything change in `v2` regarding this? Because in `v1.11.x` this was working perfectly in the same way: [hastebin.com/routes.js](http://hastebin.com/upidadusum.js)

**Comment by jamuhl** [comment]
v1 did change on i18next and on req.lng. but like i tried to explain....setting in on 18next is dangerous and would lead to issues where stuff gets not translated in current users language.

why you need the language on i18next? all your translations demands should be inside a request....
