### ISSUE TITLE
Header detection not working

### ISSUE THREAD

**Issue by duvillierA** [i18next/i18next-express-middleware#7]
Hi,

First of all, congrats for this project.

Below my Request Headers and configurations

```js
// initalizer
export default function (i18next, i18nextMiddleware) {
  i18next
  .use(Backend)
  .use(i18nextMiddleware.LanguageDetector)
  .init({
    backend: {
      // path where resources get loaded from
      loadPath: path.join(__dirname, '..', '/locales/{{lng}}/{{ns}}.json'),
      // path to post missing resources
      addPath: path.join(__dirname, '..', '/locales/{{lng}}/{{ns}}.missing.json'),
      // jsonIndent to use when storing json files
      jsonIndent: 2
    },
    fallbackLng: config.locales.fallbackLng,
    whitelist: config.locales.whitelist,
    preload: config.locales.whitelist
    //, debug: debug.enabled
  })
  debug('i18next initialized')
}
```
````js
initializer.i18next(i18next, i18nextMiddleware)
app.use(i18nextMiddleware.handle(i18next))
```

Everytime i request with custom `accept-language` header (see below), the language in `req.language` rolling back to my `fallbackLng`

```
Content-Type: application/json
Accept-Language: en
Cache-Control: no-cache
```

However, It's working with queryString paramater like lng=en

Any solutions relative to my issue?

**Comment by jamuhl** [comment]
not sure but Accept-Language should be something like: `Accept-Language: da, en-gb;q=0.8, en;q=0.7``

see:  http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html 14.4

detection is like: https://github.com/i18next/i18next-express-middleware/blob/master/src/languageLookups/header.js#L18

**Comment by jamuhl** [comment]
if not the case PR would be welcome to support header not providing weighted languages (pure strings in format `en`) or i could add this and publish new version.

**Comment by dsine-de** [comment]
Seems like I have the same problem. My ```req.headers['accept-language']``` is 
```
de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
```

The ```found``` variable in ```header.js``` returns: ```[ 'de-DE', 'de', 'en-US', 'en' ]``` but anyway ```req.language / req.languages``` just return the fallbackLng in my routes (en).

**Comment by jamuhl** [comment]
can you try with v0.1.1 i just published....should fix the issue.

**Comment by dsine-de** [comment]
Great, thank you - that works.

**Comment by duvillierA** [comment]
@jamuhl 

hi, does not looks to work for me : 

```js
TypeError: Cannot read property 'forEach' of undefined
    at /Users/userName/Documents/projects/projectName/node_modules/i18next-express-middleware/lib/LanguageDetector.js:103:19
    at Array.forEach (native)
    at LanguageDetector.detect (/Users/userName/Documents/projects/projectName/node_modules/i18next-express-middleware/lib/LanguageDetector.js:97:22)
    at /Users/userName/Documents/projects/projectName/node_modules/i18next-express-middleware/lib/index.js:36:96
    at Layer.handle [as handle_request] (/Users/userName/Documents/projects/projectName/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/userName/Documents/projects/projectName/node_modules/express/lib/router/index.js:312:13)
    at /Users/userName/Documents/projects/projectName/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/userName/Documents/projects/projectName/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/userName/Documents/projects/projectName/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/Users/userName/Documents/projects/projectName/node_modules/body-parser/lib/types/json.js:100:40)
```

**Comment by duvillierA** [comment]
@jamuhl 

Found a bug, see below : 

Issue code : https://github.com/i18next/i18next-express-middleware/blob/master/src/LanguageDetector.js#L56

```js
let detections = this.detectors[detectorName].lookup(req, res, this.options);
if (typeof detection === 'string') detections = [detections];
```
should be
```js
if(!detections) return
if (typeof detections === 'string') detections = [detections];
```
